name: Build libs

on: [ push, pull_request, workflow_dispatch ]

jobs:
  build_pkg:
    runs-on: ubuntu-20.04
    steps:

    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 1

    - name: Checkout Dependecies
      run: |
        curl -sL https://github.com/LightningMods/libtest/blob/main/mbedtls-2.16.6.tar?raw=truez | tar xvf mbedtls-2.16.6.tar
        curl -sL https://github.com/LightningMods/libtest/blob/main/curl-7.64.1.tar?raw=truez | tar xvf curl-7.64.1.tar
        wget https://raw.githubusercontent.com/LightningMods/libtest/main/openorbis.cmake

    - name: Set env vars
      id: slug
      run: |
        echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-8)"
        echo "pkg_file=IV0000-APOL00004_00-APOLLO0000000PS4.pkg" >> $GITHUB_ENV
        echo "llvm_ver=12.0" >> $GITHUB_ENV

      # temporary release until 0.53 is released
    - name: Download OpenOrbis Toolchain
      run: |
        curl -sL https://github.com/illusion0001/OpenOrbis-PS4-Toolchain/releases/download/0.0.1.416/toolchain.tar.gz | tar xvz -C ./
        echo "OO_PS4_TOOLCHAIN=${GITHUB_WORKSPACE}/OpenOrbis/PS4Toolchain" >> $GITHUB_ENV

    - name: Cache LLVM and Clang
      id: cache-llvm
      uses: actions/cache@v3
      with:
        path: ./llvm
        key: llvm-${{ env.llvm_ver }}

    - name: Install LLVM and Clang
      uses: KyleMayes/install-llvm-action@v1
      with:
        version: ${{ env.llvm_ver }}
        cached: ${{ steps.cache-llvm.outputs.cache-hit }}

    - name: Install mbedtls library
      working-directory: mbedtls-2.16.6
      run: |
        mkdir orbis && cd orbis
        cmake --toolchain ../../openorbis.cmake .. -DCMAKE_BUILD_TYPE=Release -DENABLE_TESTING=FALSE -DENABLE_PROGRAMS=FALSE -DMBEDTLS_FATAL_WARNINGS=0
        make mbedtls
        cp library/*.a "${OO_PS4_TOOLCHAIN}/lib"
        cp -R ../include/mbedtls "${OO_PS4_TOOLCHAIN}/include/"

    - name: Install libcurl library
      working-directory: curl-7.64.1
      run: |
        sed -i '54d' include/curl/curl.h
        mkdir orbis && cd orbis
        cmake --toolchain ../../openorbis.cmake .. -DCMAKE_USE_MBEDTLS=1 -DUSE_UNIX_SOCKETS=0 -DENABLE_THREADED_RESOLVER=0 -DENABLE_IPV6=0
        make libcurl
        cp lib/libcurl.a "${OO_PS4_TOOLCHAIN}/lib"
        ls lib

    - name: Compress output
      working-directory: curl-7.64.1
      run: |
        tar -zcvf build.tar.gz ${OO_PS4_TOOLCHAIN}/lib/libcurl.a ${OO_PS4_TOOLCHAIN}/lib/libmbedtls*.a lib
    - uses: actions/upload-artifact@v3.1.1
      with:
        name: build-libs
        path: build.tar.gz
        retention-days: 5
